id: ABE9FE5B7
base_file: f0993.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:09:57.947171
  last_modified_at: 2022-05-31 05:09:57.947178
