id: ABE9FE5B7
base_file: f2827.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:09:57.948861
  last_modified_at: 2022-05-31 05:09:57.948865
