id: ABE9FE5B7
base_file: f8F7F.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:09:57.951892
  last_modified_at: 2022-05-31 05:09:57.951896
