id: ABE9FE5B7
base_file: fE248.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:09:57.967008
  last_modified_at: 2022-05-31 05:09:57.967014
