id: ABE9FE5B7
base_file: fA24A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:09:57.958143
  last_modified_at: 2022-05-31 05:09:57.958145
