id: ABE9FE5B7
base_file: f9AB4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:09:57.955606
  last_modified_at: 2022-05-31 05:09:57.955610
